# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Farmland Financial Review
email: emhardin210@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Farmland Financial Review is managed by Erin M. Hardin, PhD Candidate, Texas A&M University & Research Assistant, Agriculture & Food Policy Center at Texas A&M.  The goal of this site is to provide a collection of information pertinant to farmland investments.
baseurl: "/farmlandfinancial" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: FarmlandFinancial
#github_username:  FarmlandFinancial

# Build settings
markdown: kramdown
collections:
  - graphs
    
